# language_model: "intfloat/multilingual-e5-base"
language_model: "/leonardo_scratch/fast/IscrC_TIGeR/relik-ml/relik-ric/experiments/me5-base-wikipedia-inorder-nohn-mewsli3Meval/2024-10-18/09-12-17/retriever/question_encoder"

pl_module:
  _target_: relik.retriever.lightning_modules.pl_modules.GoldenRetrieverPLModule
  model:
    _target_: relik.retriever.pytorch_modules.model.GoldenRetriever
    question_encoder: ${model.language_model}
    # passage_encoder: ${model.language_model}
    document_index: ${index}
    loss_type: ${loss}
  optimizer: ${optimizer}
  lr_scheduler: ${scheduler}
